#!/bin/bash
current=`pwd`
export PATH=$PATH:$current
GTKDIALOG=gtkdialog 
export MAIN_DIALOG=' 
<window title="Koch Snowflake" icon-name="gtk-about" resizable="false" width-request="700" height-request="500"> 
<vbox> 
	<frame '`gettext $" Successions "`'>
		<text use-markup="true">
			<label>"'`gettext $" Enter the number of successions :  "`'"</label>
		</text>
	<hbox space-fill="true"> 
		<combobox>	 
			<variable>succession</variable> 
			<item>1</item> 
			<item>2</item> 
			<item>3</item>
			<item>4</item>
			<item>5</item>
			<item>6</item>
			<item>7</item> 
		</combobox> 
	</hbox> 
	</frame>
<hseparator width-request="240"></hseparator> 
	<frame '`gettext $" Size selection "`'>
		<text use-markup="true">
			<label>"'`gettext $" Enter the size of the triangle :  "`'"</label>
		</text>
	<hbox space-fill="true"> 
		<combobox>	 
			<variable>size</variable> 
			<item>1</item>
			<item>2</item> 
			<item>3</item>
			<item>4</item> 
			<item>5</item>
		</combobox> 
	</hbox> 
	</frame>
<hseparator width-request="240"></hseparator> 
	<frame '`gettext $" Color selection "`'>
		<text use-markup="true">
			<label>"'`gettext $" Enter the color of the Koch curve : "`'"</label>
		</text>
		<text use-markup="true">
			<label>"'`gettext $" 1.RED         2.GREEN          3.BLUE "`'"</label>
		</text>
		<text use-markup="true">
			<label>"'`gettext $" [ 1 - 3 ]  "`'"</label>
		</text>
	<hbox space-fill="true"> 
		<combobox>	 
			<variable>color</variable>
			<item>1</item> 
			<item>2</item> 
			<item>3</item> 
		</combobox>
	</hbox> 
	</frame> 
<hseparator width-request="240"></hseparator> 
	<hbox> 
		<button ok></button> 
	</hbox> 
</vbox> 
</window> 
'
$(glc koch.cpp)
echo "Compilation done." 
case $1 in 
	-d | --dump) echo "$MAIN_DIALOG" ;; 
	*) I=$IFS; IFS="" 
	for STATEMENTS in  $($GTKDIALOG --program=MAIN_DIALOG --center); do 
   		eval $STATEMENTS 
	done 
	if [ $EXIT == "abort" ]
	then
		exit 0
	fi
	if [ $succession -gt 7 ] || [ $succession -lt 0 ] || [[ -n ${succesion//[0-9]/} ]]; then zenity --info --title="Horopter Inc." --ok-label="Finish" --width="500" --height="300" --text "Invalid entry for number of successions. Click Finish to exit."; exit ;fi
	if [ $size -gt 5 ] || [ $size -lt 1 ] || [[ -n ${size//[0-9]/} ]]; then zenity --info --title="Horopter Inc." --ok-label="Finish" --width="500" --height="300" --text "Invalid entry for initial size. Click Finish to exit."; exit ;fi
	if [ $color -gt 3 ] || [ $color -lt 1 ] || [[ -n ${color//[0-9]/} ]]; then zenity --info --title="Horopter Inc." --ok-label="Finish" --width="500" --height="300" --text "Invalid entry for the color. Click Finish to exit."; exit ;fi
	IFS=$I
	input=`echo "$succession $size $color"`
	./graph.out "$input"
	succession=$(echo $succession + 2 | bc)
	size=$(echo $size + $size | bc)
	input=`echo "$succession $size $color"`
	$(glc zoom.cpp)
	./graph.out "$input";; 
esac

